---
- name: Clean up GlusterFS mountpoint
  file:
     state: absent
     path: "{{glusterfs_perf_mountpoint|default('/mnt/glusterfs')}}/{{item}}"
  with_items:
     - file_dstdir
     - file_srcdir
     - network_shared
  delegate_to: "{{ glusterfs_perf_client | default(glusterfs_perf_server) }}"
  run_once: true

# Run the perf tool on the mountpoint
- name: Run mkdir/rmdir tests
  command:
  args:
    argv:
      - /usr/src/smallfile/smallfile_cli.py
      - --stonewall
      - N
      - --operation
      - "{{ item }}"
      - --threads
      - "{{ glusterfs_perf_smallfile_threads }}"
      - --file-size
      - "{{ glusterfs_perf_smallfile_file_size }}"
      - --files
      - "{{ glusterfs_perf_smallfile_num_of_files }}"
      - --top
      - "{{ glusterfs_perf_mountpoint | default('/mnt/glusterfs') }}"
      - --host-set
      - "{{ gluster_clients }}"
      - --output-json
      - "{{glusterfs_perf_resdir}}/smallfile/{{item}}"
  delegate_to: "{{ glusterfs_perf_client | default(glusterfs_perf_server) }}"
  run_once: true
  with_items:
     - mkdir
     - rmdir
