---
# This task creates ssh keys on each host, or uses existing keys and populates
# the authorized keys on other hosts (in scope of the play) to trust the
# existing or generated key.

- name: Generate ssh key for ansible user
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa

- name: Copy ssh public key
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_keys

- name: Deploy keys on all hosts
  authorized_key: user=root key="{{ item[0] }}"
  delegate_to: "{{ item[1] }}"
  with_nested:
   - "{{ ssh_keys.stdout }}"
   - "{{groups['all']}}"
